<?php require('template/header.phtml') ?>

    <!-- CRUD Buttons-->
    <form method="post">
        <label>Create, View, Update or Delete a Shift Or User:</label>
        <br>
        <br>
        <input type="submit" name="createShiftBtn" value="Create Shift" class="btn btn-light">
        <input type="submit" name="createUsersBtn" value="Create User" class="btn btn-light">
        <input type="submit" name="viewScheduleBtn" value="View Schedule" class="btn btn-light">
<!--        <a href="ViewSchedule.php" class="btn btn-light">View Schedule</a>-->
        <input type="submit" name="viewUsersBtn" value="View Users" class="btn btn-light">
    </form>
    <br>

    <!-- Form that is created when Create Records button is pressed -->
<?php if (isset($_POST['createShiftBtn'])) { ?>
    <h2>Create Shift</h2>
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
        <label for="username">Doctor:</label>
        <select name="username" id="username" class="form-control">
            <option value="" disabled selected hidden>Select a Doctor...</option>
            <?php foreach ($view->userSet as $doctor): ?>
                <option value="<?= htmlspecialchars($doctor->getUsername()) ?>">
                    <?= htmlspecialchars($doctor->getUsername()) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <label for="shiftType">Shift Type:</label>
        <br>
        <select name="shiftType" id="shiftType" class="form-control">
            <option value="" disabled selected hidden>Select a Shift Type...</option>
            <?php foreach ($view->shiftTypeSet as $shiftType): ?>
                <option value="<?= htmlspecialchars($shiftType->getShiftType()) ?>">
                    <?= htmlspecialchars($shiftType->getShiftType()) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <label for="shiftStart">Shift Start:</label>
        <input type="datetime-local" id="shiftStart" name="shiftStart" class="form-control" required>

        <label for="shiftEnd">Shift End:</label>
        <input type="datetime-local" id="shiftEnd" name="shiftEnd" class="form-control" required>

        <input type="submit" name="createShift" class="form-control" required>
    </form>

    <!-- Form that is created when Create Users button is pressed --> ,
<?php } elseif (isset($_POST['createUsersBtn'])) { ?>
    <h2>Create User</h2>
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" class="form-control" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" class="form-control" required>
        <label for="usertype">User Type:</label>
<!--        <input type="text" id="usertype" name="usertype" class="form-control" required>-->
        <select name="userType" id="userType" class="form-control">
            <option value="" disabled selected hidden>Select a User Type...</option>
            <?php foreach ($view->userTypeSet as $userType): ?>
                <option value="<?= htmlspecialchars($userType->getUserType()) ?>">
                    <?= htmlspecialchars($userType->getUserType()) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <input type="submit" name="createUser" class="form-control" required>
    </form>

    <!-- Form that is created when View Records button is pressed -->
<?php } elseif (isset($_POST['viewScheduleBtn'])) {
    header("Location: ViewSchedule.php");
    exit();
?>

    <!-- Form that is created when View Users button is pressed -->
<?php } elseif (isset($_POST['viewUsersBtn'])) { ?>
    <h2>View Users</h2>
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
        <table class="table table-hover">
            <thead>
            <tr class="page-break">
                <th>ID</th>
                <th>Username</th>
                <th>Password</th>
                <th>User Type</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($view->userSet as $user) {
                echo '<tr> <td>' . $user->getUserID() .
                    '</td> <td>' . $user->getUsername() .
                    '</td> <td>' . $user->getPassword() .
                    '</td> <td>' . $user->getUsertype() .
                    '</td> <td> <div class="btn-group" role="group" aria-label="Record Actions"><a class="btn btn-info" href="updateUser.php?id=' . $user->getUserID() . '">Edit</a>&nbsp;
                    <a class="btn btn-danger" href="deleteUser.php?id=' . $user->getUserID() . '">Delete</a></div></td>';
            } ?>
            </tbody>
        </table>
    </form>
<?php } ?>

<?php require ('template/footer.phtml');
