<?php require('template/header.phtml') ?>

    <!-- CRUD Buttons-->
    <form method="post">
        <label>Create, Read, Update or Delete a Delivery Record Or User:</label>
        <br>
        <br>
        <input type="submit" name="createRecordsBtn" value="Create Record" class="btn btn-light">
        <input type="submit" name="createUsersBtn" value="Create User" class="btn btn-light">
        <input type="submit" name="viewRecordsBtn" value="View Records" class="btn btn-light">
        <input type="submit" name="viewUsersBtn" value="View Users" class="btn btn-light">
    </form>
    <br>
    <!-- Form that is created when Create Records button is pressed -->
<?php if (isset($_POST['createRecordsBtn'])) { ?>
    <h2>Create Record</h2>
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" class="form-control" required>
        <label for="address">Address:</label>
        <input type="text" id="address" name="address" class="form-control" required>
        <label for="city">City:</label>
        <input type="text" id="city" name="city" class="form-control" required>
        <label for="postcode">Postcode:</label>
        <input type="text" id="postcode" name="postcode" class="form-control" required>
        <label for="deliverer">Deliverer:</label>
        <input type="text" id="deliverer" name="deliverer" class="form-control" required>
        <label for="lat">Latitude:</label>
        <input type="text" id="lat" name="lat" class="form-control" required>
        <label for="long">Longitude:</label>
        <input type="text" id="long" name="long" class="form-control" required>
        <label for="status">Status:</label>
        <input type="text" id="status" name="status" class="form-control" required>
        <input type="submit" name="createRecord" class="form-control" required>
    </form>
    <!-- Form that is created when Create Users button is pressed --> ,
<?php } elseif (isset($_POST['createUsersBtn'])) { ?>
    <h2>Create User</h2>
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" class="form-control" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" class="form-control" required>
        <label for="usertype">User Type:</label>
        <input type="text" id="usertype" name="usertype" class="form-control" required>
        <input type="submit" name="createUser" class="form-control" required>
    </form>
    <!-- Form that is created when View Records button is pressed -->
<?php } elseif (isset($_POST['viewRecordsBtn'])) { ?>
    <h2>View Records</h2>
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
        <table class="table table-hover">
            <thead>
            <tr class="page-break">
                <th>ID</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>Postcode</th>
                <th>Deliverer</th>
                <th>Lat</th>
                <th>Long</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
<!--            --><?php //foreach ($view->deliveryPointSet as $deliveryPoint){
//                echo '<tr> <td>' . $deliveryPoint->getID() .
//                    '</td> <td>' . $deliveryPoint->getName() .
//                    '</td> <td>' . $deliveryPoint->getAddress() .
//                    '</td> <td>' . $deliveryPoint->getCity() .
//                    '</td> <td>' . $deliveryPoint->getPostcode() .
//                    '</td> <td>' . $deliveryPoint->getDeliverer() .
//                    '</td> <td>' . $deliveryPoint->getLat() .
//                    '</td> <td>' . $deliveryPoint->getLong() .
//                    '</td> <td>' . $deliveryPoint->getStatus() .
//                    '</td> <td> <div class="btn-group" role="group" aria-label="Record Actions"><a class="btn btn-info" href="updateRecord.php?id=' . $deliveryPoint->getID() . '">Edit</a>&nbsp;
//                    <a class="btn btn-danger" href="deleteRecord.php?id=' . $deliveryPoint->getID() . '">Delete</a></div></td>';
//            } ?>
            </tbody>
        </table>
    </form>
    <!-- Form that is created when View Users button is pressed -->
<?php } elseif (isset($_POST['viewUsersBtn'])) { ?>
    <h2>View Users</h2>
    <form action=" <?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-control">
        <table class="table table-hover">
            <thead>
            <tr class="page-break">
                <th>ID</th>
                <th>Username</th>
                <th>Password</th>
                <th>User Type</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
<!--            --><?php //foreach ($view->deliveryUserSet as $deliveryUser) {
//                echo '<tr> <td>' . $deliveryUser->getUserID() .
//                    '</td> <td>' . $deliveryUser->getUsername() .
//                    '</td> <td>' . $deliveryUser->getPassword() .
//                    '</td> <td>' . $deliveryUser->getUsertype() .
//                    '</td> <td> <div class="btn-group" role="group" aria-label="Record Actions"><a class="btn btn-info" href="updateUser.php?id=' . $deliveryUser->getUserID() . '">Edit</a>&nbsp;
//                    <a class="btn btn-danger" href="deleteUser.php?id=' . $deliveryUser->getUserID() . '">Delete</a></div></td>';
//            } ?>
            </tbody>
        </table>
    </form>
<?php } ?>

<?php require ('template/footer.phtml');
