
</section>
</div>
</div>
</main>




<!--    <footer class="footer fixed-bottom mt-auto py-3 bg-light">-->
<!--        <div class="container">-->
<!--            <span class="text-muted">Web-site development using the MVC design pattern and the Bootstrap CSS framework.</span>-->
<!--        </div>-->
<!--    </footer>-->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>