<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="/css/my-style.css" rel="stylesheet">

    <title>Online Rota - <?php echo $view->pageTitle; ?></title>
</head>

<body class="d-flex flex-column h-100">
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Fixed navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                    </li>
                    <li class="nav-item">
                        <?php if (isset($_SESSION['login'])){
                            echo '<form method="post" action="login.php" class="form-inline">
                            <input type="submit" name="logoutbutton" value="Log Out" class="btn btn-sm btn-outline-secondary">
                        </form>';
                        }
                        else {
                            echo '<form method="post" action="login.php" class="form-inline">
                            <input type="submit" name="loginbutton" value="Log In" class="btn btn-sm btn-outline-secondary">
                        </form>';
                        }?>
                    </li>
                </ul>
            </div>
            <!--                <form class="form-inline">-->
            <!--                    <button class="btn btn-outline-success" type="button" name="loginbutton">Log In</button>-->
            <!--                </form>-->
        </div>
    </nav>
</header>

<main class="flex-shrink-0">

    <div class="container">
        <div class="row">
            <div id="title" class="col-xs-12">
<!--                <img src="images/new_uos_logo.jpg" alt="Salford University"/>-->
                <h1><?php echo $view->pageTitle ?> </h1>

                <!-- https://getbootstrap.com/docs/5.2/examples/sticky-footer-navbar/ -->

            </div>
        </div>

        <div class="row">
            <section id="content" class="col-xs-6 col-sm-9 col-md-10">